config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  # Authentication, registration
  devise_for :users, skip: :registrations,
  controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'users/registrations',
      as: :user_registration do
        get :cancel
      end
  end

  get '/users', to: redirect('/users/sign_in')


  # Admin Dashboard
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad


  root 'home#index'

  # Error handling
  match '404', to: 'error#not_found', via: :all
  match '500', to: 'error#server_error', via: :all
  match '418', to: 'error#teapot', via: :all

  # Schedules
  get 'schedule', to: 'schedules#current', as: 'current_schedule'
  get 'schedule/next', to: 'schedules#next', as: 'next_schedule'

  # Standalone player
  # POST required for Facebook Tab Page.
  # TODO: the above was written by prev. webmaster. Check whether it's true
  match 'listen', to: 'player#listen', as: "listen", via: [:get, :post]

  # Feed RSS
  get 'feed', to: 'feed#general', as: 'feed'

  # Posts
  resources :posts, only: ['show', 'index']

  # Teams
  resources :teams, only: ['show'] do
    get 'all_posts', on: :member, as: 'all_posts'
  end

  # Events
  resources :events, only: ['show']

  # Tags
  resources :tags, only: ['show']

  # Shows
  resources :shows, only: ['show', 'index'] do
    # /shows/all will also display shows not in schedule
    get 'all', on: :collection
    resources :podcasts, only: ['show']
  end

  # Techteam page
  get 'techteam', to: 'techteam#index', as: 'techteam'

  # FreshAir.org.uk IT instructions for users
  get 'help', to: 'static#help'

  # Report issue page
  get 'issue', to: 'issue#report', as: 'issue'
  post 'issue', to: 'issue#submit'
  get 'issue/submitted', to: 'issue#submitted', as: 'issue_submitted'


  scope 'api' do
    get 'users/:email/shows', to: 'api#shows_for_user', :constraints => { email: /[\w|.|-]+@[\w|.|-]+/ }
    get 'schedules/current', to: 'api#current_schedule'
    get 'shows/all', to: 'api#all_shows'
    get 'shows/:slug', to: 'api#show_by_slug'
    get 'shows/:slug/check-broadcast-time/:start(-:end)', to: 'api#check_broadcast_time', :constraints => { start: /[0-9]+/, end: /[0-9]+/ }
    get 'podcasts/:show_slug', to: 'api#podcasts_by_show'
  end

  # Static pages
  # (should be at the end of the file not to mess with other routes)
  resources :pages, path: '/', only: ['show'] do
    resources :sub_pages, path: '/', only: ['show']
  end

end

app/models/schedule.rb
class Schedule < ApplicationRecord

  after_initialize :set_defaults

  validates :name, presence: true
  validates :name, uniqueness: true
  validates_with ScheduleValidator

  # https://stackoverflow.com/questions/16782990/rails-how-to-populate-parent-object-id-using-nested-attributes-for-child-obje
  has_many :assignments, class_name: 'ScheduleAssignment', dependent: :delete_all, :inverse_of => :schedule

  accepts_nested_attributes_for :assignments, :allow_destroy => true

  def past?
    self.end_date < Date.today
  end

  def future?
    self.start_date > Date.today
  end

  def current?
    !self.future? && !self.past?
  end

  def expiring?
    (self.end_date - Date.today).to_i <= 10
  end

  def self.current
    Schedule.where('start_date <= ? AND end_date >= ?', Date.today, Date.today).take
  end

  def self.next
    Schedule.where('start_date >= ? ', Date.tomorrow).order(start_date: :asc).first
  end

  def assignments_on(day)
    # day is an integer 1-7
    self.assignments.where(day_of_week: day)
  end

  # Assumption: the schedule won't change between the start_time and end_time
  # This can't happen because of how schedules are modelled: they are assumed
  # to start at midnight of a day and assignments cannot end after 23.59
  def show_valid_for_time?(show, start_time, end_time=nil)
    # Select schedule assignments on same week day corresponding to start time for show
    assignments = self.assignments_on(Time.at(start_time).to_date.cwday)

    # Select assignments involving passed show
    assignments = assignments.where(show: show)

    # Select schedule assignments with start time of show equal to start time of assignments
    assignments = assignments.select do
      |a| a.start_time.utc.strftime( "%H:%M:%S" ) == Time.at(start_time).utc.strftime( "%H:%M:%S" )
    end


    return (not assignments.empty?) if end_time == nil

    # Select end_times such that they don't come before the show's end time
    valid_times = assignments.map(&:end_time).select { |time| time.utc.strftime( "%H:%M:%S" ) >=  Time.at(end_time).utc.strftime( "%H:%M:%S" )}

    not valid_times.empty?
  end


  def self.for_time(time)
    date = Time.at(time).to_date
    Schedule.where('start_date <= ? AND end_date >= ?', date, date).take
  end

  def clash_with?(schedule)
    # Two schedules clash if, either the first contains the second,
      (((self.start_date <= schedule.start_date) && (self.end_date >= schedule.end_date)) ||
        # or the first starts while the second is on,
        ((self.start_date >= schedule.start_date) && (self.start_date <= schedule.end_date)) ||
        # or if the first ends while the second is on
        ((self.end_date >= schedule.start_date) && (self.end_date <= schedule.end_date)))
  end

  def compatible_with_times?(start_time, end_time)
    # Note: this method should be used to check whether datetimes clash with some
    # assignments and won't check whether datetimes are in the schedule's frame
    # of validity
    # Assumption: bookings' start and end times are on the same day
    day_of_week = start_time.wday

    booking = ScheduleAssignment.new(
      start_time: start_time.to_time,
      end_time: end_time.to_time,
      day_of_week: start_time.wday
    )

    assignments = self.assignments_on(day_of_week)

    return booking.compatible_with?(assignments)
  end

  private

    def set_defaults
      self.is_free_schedule = false if self.is_free_schedule.nil?
    end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  def current
    @title = 'Schedule'
    @schedule = Schedule.current
    @next_schedule = Schedule.next
    @days_of_week = WeekService.days_dic
  end

  def next
    @title = 'Next schedule'
    @schedule = Schedule.next

    if @schedule.nil?
      # If there's no next schedule, go to current schedule page
      redirect_to current_schedule_path
    end

    @days_of_week = WeekService.days_dic
  end

end

app/views/schedules/current.html.erb
<% if @schedule.nil? %>
  <em class="simple-notice">No current schedule</em>
<% else %>
  <div>
    <nav class="main-nav">
      <ul>
        <% @days_of_week.each do |day, i| %>
          <li id="<%= day.downcase %>" class="tablinks" onclick="openTab(event, '<%= day %>')">
            <%= day %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>

  <% if @schedule.expiring? %>
    <div class="messages messages-notice">
      This schedule will be valid until <%= format_date @schedule.end_date %>
    </div>
  <% end %>

  <% @days_of_week.each do |day, i| %>
    <div id="<%= day %>" class="tabcontent">
      <% if @schedule.assignments_on(i).empty? %>
      <em class="simple-notice">Nothing scheduled</em>
      <% end %>
      <% @schedule.assignments_on(i).order(start_time: :asc).each do |assignment| %>
      <div> (
        <%= format_time(assignment.start_time) %>
        -
        <%= format_time(assignment.end_time) %>
        )
        <%= link_to assignment.show.title, show_path(assignment.show)%>
      </div>
      <% end %>
    </div>

  <% end %>
<% end %>

<% unless @next_schedule.nil? %>
    <p>
      A <%= link_to 'new schedule', next_schedule_path %> will be in place
      from <%= format_date @next_schedule.start_date %>
    </p>
<% end %>

<script>
// Get the element with id="defaultOpen" and click on it
  document.getElementById("<%= Date.today.strftime("%A").downcase %>").click();
</script>

app/views/schedules/next.html.erb
<div>
  <nav class="main-nav">
    <ul>
      <% @days_of_week.each do |day, i| %>
        <li id="<%= day.downcase %>" class="tablinks" onclick="openTab(event, '<%= day %>')">
          <%= day %>
        </li>
      <% end %>
    </ul>
  </nav>
</div>

<div class="messages messages-notice inline">
  This schedule will be valid from <%= format_date @schedule.start_date %>:
  you are looking into the future, which is mysterious and uncertain.
  This schedule may be subject to change.
</div>

<% @days_of_week.each do |day, i| %>
  <div id="<%= day %>" class="tabcontent">
    <% if @schedule.assignments_on(i).empty? %>
    <em class="simple-notice">Nothing scheduled</em>
    <% end %>
    <% @schedule.assignments_on(i).order(start_time: :asc).each do |assignment| %>
    <div> (
      <%= format_time(assignment.start_time) %>
      -
      <%= format_time(assignment.end_time) %>
      )
      <%= link_to assignment.show.title, show_path(assignment.show)%>
    </div>
    <% end %>
  </div>
<% end %>




<script>
// Get the element with id="defaultOpen" and click on it
  document.getElementById("<%= Date.today.strftime("%A").downcase %>").click();
</script>