config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  # Authentication, registration
  devise_for :users, skip: :registrations,
  controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'users/registrations',
      as: :user_registration do
        get :cancel
      end
  end

  get '/users', to: redirect('/users/sign_in')


  # Admin Dashboard
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad


  root 'home#index'

  # Error handling
  match '404', to: 'error#not_found', via: :all
  match '500', to: 'error#server_error', via: :all
  match '418', to: 'error#teapot', via: :all

  # Schedules
  get 'schedule', to: 'schedules#current', as: 'current_schedule'
  get 'schedule/next', to: 'schedules#next', as: 'next_schedule'

  # Standalone player
  # POST required for Facebook Tab Page.
  # TODO: the above was written by prev. webmaster. Check whether it's true
  match 'listen', to: 'player#listen', as: "listen", via: [:get, :post]

  # Feed RSS
  get 'feed', to: 'feed#general', as: 'feed'

  # Posts
  resources :posts, only: ['show', 'index']

  # Teams
  resources :teams, only: ['show'] do
    get 'all_posts', on: :member, as: 'all_posts'
  end

  # Events
  resources :events, only: ['show']

  # Tags
  resources :tags, only: ['show']

  # Shows
  resources :shows, only: ['show', 'index'] do
    # /shows/all will also display shows not in schedule
    get 'all', on: :collection
    resources :podcasts, only: ['show']
  end

  # Techteam page
  get 'techteam', to: 'techteam#index', as: 'techteam'

  # FreshAir.org.uk IT instructions for users
  get 'help', to: 'static#help'

  # Report issue page
  get 'issue', to: 'issue#report', as: 'issue'
  post 'issue', to: 'issue#submit'
  get 'issue/submitted', to: 'issue#submitted', as: 'issue_submitted'


  scope 'api' do
    get 'users/:email/shows', to: 'api#shows_for_user', :constraints => { email: /[\w|.|-]+@[\w|.|-]+/ }
    get 'schedules/current', to: 'api#current_schedule'
    get 'shows/all', to: 'api#all_shows'
    get 'shows/:slug', to: 'api#show_by_slug'
    get 'shows/:slug/check-broadcast-time/:start(-:end)', to: 'api#check_broadcast_time', :constraints => { start: /[0-9]+/, end: /[0-9]+/ }
    get 'podcasts/:show_slug', to: 'api#podcasts_by_show'
  end

  # Static pages
  # (should be at the end of the file not to mess with other routes)
  resources :pages, path: '/', only: ['show'] do
    resources :sub_pages, path: '/', only: ['show']
  end

end

app/views/shared/_aside.html.erb
<aside>
  <label for="top-toggler" class="expand-top">
    <i class="fa fa-angle-down" aria-hidden="true"></i>
  </label>
  <%= link_to root_path do %>
    <%= image_tag 'logo-white.png', class: 'logo-white' %>
  <% end %>
  <div data-turbolinks-permanent id="player">
    <div class="on-air">
      <%= image_tag 'default-cover.png', id: 'player-default-picture'%>
      <img src="" style="display:none;" id="player-picture">

      <div class="on-air-info">
        <div>
          <h4 id="player-status">FreshSounds</h4>
          <p id="player-title">Best music from FreshAir</p>
          <a href="#" id="player-details" style="display:none;">Details</a>
          <span id="player-space" style="display:none;">&nbsp;</span>
          <%= link_to 'View shows', shows_path %><br>
        </div>
        <div class="player-buttons">
          <%= link_to 'Schedule', current_schedule_path, class: 'button button-transparent' %>
          <span id="audio-control" class="button button-blue">
            <span id="play-icon"><i class="fa fa-play" aria-hidden="true"></i></span>
            <span id="audio-control-txt">Play now</span>
          </span>
        </div>
      </div>
    </div>
  </div>

  <section class="events">
    <% if events.size > 0 %>
      <h2>Upcoming events.</h2>
      <% events.each do |event| %>
        <div class="event">
          <%= link_to event.name, event_path(event) %>
          <span class="date"><%= format_date_small event.start %></span>
        </div>
      <% end %>
    <% end %>
  </section>

  <section class="twitter">
    <h2>Twitter feed.</h2>
    <%= render partial: 'shared/tweet', collection: tweets, as: :tweet %>
  </section>

  <section class="message-studio">
    <h2>Message studio.</h2>
    <form>
      <input id="message-author" type="text" name="" value="" placeholder="Type name, press enter">
      <input id="message-content" type="text" name="" value="" placeholder="Type message, press enter">
      <div id="message-info">
      </div>
    </form>
  </section>

  <!-- <hr>
  <div class="waverley-care-logo"><a href="#"><img src="waverley_care.jpg" alt="Waverley Care"></a></div> -->
</aside>

app/views/shared/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-40410225-2', 'auto');
  ga('send', 'pageview');

</script>

app/views/shared/_messages.html.erb
<%# TODO: this view is shit. Fix %>
<% unless locals[:type].nil? %>
  <%
      case locals[:type]
      when :alert
        messages_class = "messages-alert"
        icon       = "fa-exclamation-triangle fa-red"
      when :success
        messages_class = "messages-success"
        icon       = "fa-check fa-green"
      when :notice
        messages_class = "messages-notice"
        icon       = "fa-info-circle fa-blue"
      end
  %>

    <div class="messages <%= messages_class %>">
      <i class="fa <%= icon %> aria-hidden="true""></i>
      <div class="error-list">
        <%= yield %>
      </div>
    </div>

<% else %>
  <%
    alert_messages = locals[:messages]["alert"]
    success_messages = locals[:messages]["success"]
    notice_messages = locals[:messages]["notice"]
  %>
  <% unless alert_messages.nil? %>
    <div class="messages messages-alert">
      <i class="fa fa-exclamation-triangle fa-red" aria-hidden="true"></i>
      <div class="error-list">
        <ul>
          <li><%= alert_messages %></li>
        </ul>
      </div>
    </div>
  <% end %>

  <% unless success_messages.nil? %>
    <div class="messages messages-success">
      <i class="fa fa-check fa-green" aria-hidden="true"></i>
      <div class="error-list">
        <ul>
          <li><%= success_messages %></li>
        </ul>
      </div>
    </div>
  <% end %>

  <% unless notice_messages.nil? %>
    <div class="messages messages-notice">
      <i class="fa fa-info-circle fa-blue" aria-hidden="true"></i>
      <div class="error-list">
        <ul>
          <li><%= notice_messages %></li>
        </ul>
      </div>
    </div>
  <% end %>

<% end %>

app/views/shared/_posts.html.erb
<% unless posts.empty? %>

  <% if pics == false %>
    <div class="boxes posts">
      <% posts.each do |post| %>
        <%= link_to post, class: 'post' do %>
            <div class="post-info">
              <div class="post-title">
                <%= post.title %>
              </div>
              <div class="post-caption">
                <%= post_summary(post) %>
              </div>
              <div class="post-details">
                <div>
                  <%= format_date_small post.created_at %>
                </div>
                <div>
                  <%= post.author.name %>
                </div>
              </div>
            </div>
        <% end%>
      <% end %>
    </div>
  <% else %>
    <div class="boxes posts">
      <% posts.each do |post| %>
        <%= link_to post, class: 'post' do %>
          <div class="<%= post.pic_url.nil? ? 'post-info' : 'post-info-pic' %>">

            <% unless post.pic_url.nil? %>
              <div class="post-pic">
                <%= image_tag post.pic_url %>
              </div>
            <% end %>

            <div class="title-wrapper">
              <div class="post-title">
                <%= post.title %>
              </div>
            </div>

            <% if post.pic_url.nil? %>
              <div class="post-caption">
                <%= post_summary(post) %>
              </div>
            <% end %>

          </div>
        <% end%>
      <% end %>
    </div>
  <% end %>




<% else %>
  <em class="simple-notice">No post here</em>
<% end %>

app/views/shared/_tweet.html.erb
<p class="tweet">
  <small>
    <%= auto_link_tweet(tweet) %>
    <span class="tweet-date">
      <%= link_to "https://twitter.com/statuses/#{tweet.id}", target: "_blank" do %>
        <%  format_date_time(tweet.created_at) if tweet.created_at %>
      <% end %>
    </span>
  </small>
</p>