config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  # Authentication, registration
  devise_for :users, skip: :registrations,
  controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'users/registrations',
      as: :user_registration do
        get :cancel
      end
  end

  get '/users', to: redirect('/users/sign_in')


  # Admin Dashboard
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad


  root 'home#index'

  # Error handling
  match '404', to: 'error#not_found', via: :all
  match '500', to: 'error#server_error', via: :all
  match '418', to: 'error#teapot', via: :all

  # Schedules
  get 'schedule', to: 'schedules#current', as: 'current_schedule'
  get 'schedule/next', to: 'schedules#next', as: 'next_schedule'

  # Standalone player
  # POST required for Facebook Tab Page.
  # TODO: the above was written by prev. webmaster. Check whether it's true
  match 'listen', to: 'player#listen', as: "listen", via: [:get, :post]

  # Feed RSS
  get 'feed', to: 'feed#general', as: 'feed'

  # Posts
  resources :posts, only: ['show', 'index']

  # Teams
  resources :teams, only: ['show'] do
    get 'all_posts', on: :member, as: 'all_posts'
  end

  # Events
  resources :events, only: ['show']

  # Tags
  resources :tags, only: ['show']

  # Shows
  resources :shows, only: ['show', 'index'] do
    # /shows/all will also display shows not in schedule
    get 'all', on: :collection
    resources :podcasts, only: ['show']
  end

  # Techteam page
  get 'techteam', to: 'techteam#index', as: 'techteam'

  # FreshAir.org.uk IT instructions for users
  get 'help', to: 'static#help'

  # Report issue page
  get 'issue', to: 'issue#report', as: 'issue'
  post 'issue', to: 'issue#submit'
  get 'issue/submitted', to: 'issue#submitted', as: 'issue_submitted'


  scope 'api' do
    get 'users/:email/shows', to: 'api#shows_for_user', :constraints => { email: /[\w|.|-]+@[\w|.|-]+/ }
    get 'schedules/current', to: 'api#current_schedule'
    get 'shows/all', to: 'api#all_shows'
    get 'shows/:slug', to: 'api#show_by_slug'
    get 'shows/:slug/check-broadcast-time/:start(-:end)', to: 'api#check_broadcast_time', :constraints => { start: /[0-9]+/, end: /[0-9]+/ }
    get 'podcasts/:show_slug', to: 'api#podcasts_by_show'
  end

  # Static pages
  # (should be at the end of the file not to mess with other routes)
  resources :pages, path: '/', only: ['show'] do
    resources :sub_pages, path: '/', only: ['show']
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @latest_posts = Post.order(created_at: :desc).limit(6)
    @highlights = HighlightsService.get_highlights
    @post_types = Tag.post_types
  end

end

app/views/home/index.html.erb
<nav class="main-nav">
  <ul>
    <li class="selected"><%= link_to 'Home', root_path%></li>
    <% @global_teams.each do |team| %>
      <li>
        <%= link_to team.name, team%>
      </li>
    <% end %>
    <% @global_pages.each do |page| %>
    <li><%= link_to page.title, page_path(page)%></li>
    <% end %>
  </ul>
</nav>

<% if flash.any? %>
  <%= render 'shared/messages', locals: {messages: flash} %>
<% end %>

<% unless SettingsService.get('home-header').nil? %>
  <section class="content-header">
    <%# Crucial to sanitize %>
    <%= sanitize SettingsService.get('home-header').html_safe, tags: accepted_tags, attributes: accepted_attributes %>
  </section>
<% end %>


<section class="home-grid">
  <%# The following is not very DRY but allows for treating each position differently if we ever need to %>
  <% unless @highlights.first.nil? %>
    <%= link_to @highlights.first[:element], class:'element pos-1' do %>
      <div class="filter"></div>
      <div class="pic">
        <% unless @highlights.first[:pic].nil? %>
          <%= image_tag @highlights.first[:pic] %>
        <% else %>
          <%= image_tag 'bg/dummy-1.png' %>
        <% end %>
      </div>
      <div class="title-wrapper">
        <div class="title">
          <%= @highlights.first[:title] %>
        </div>
      </div>
    <% end %>
    <% else %>
      <%= link_to '#', class:'element pos-1' do %>
        <div class="filter"></div>
        <div class="pic">
          <%= image_tag 'bg/dummy-1.png' %>
        </div>
        <div class="title-wrapper">
          <div class="title">
            Content goes here
          </div>
        </div>
      <% end %>
    <% end %>

  <% unless @highlights.second.nil? %>
    <%= link_to @highlights.second[:element], class:'element pos-2' do %>
      <div class="filter"></div>
      <div class="pic">
        <% unless @highlights.second[:pic].nil? %>
          <%= image_tag @highlights.second[:pic] %>
        <% else %>
          <%= image_tag 'bg/dummy-2.png' %>
        <% end %>
      </div>
      <div class="title-wrapper">
        <div class="title">
          <%= @highlights.second[:title] %>
        </div>
      </div>
    <% end %>
    <% else %>
      <%= link_to '#', class:'element pos-2' do %>
        <div class="filter"></div>
        <div class="pic">
          <%= image_tag 'bg/dummy-2.png' %>
        </div>
        <div class="title-wrapper">
          <div class="title">
            Content goes here
          </div>
        </div>
      <% end %>
    <% end %>


  <% unless @highlights.third.nil? %>

    <%= link_to @highlights.third[:element], class:'element pos-3' do %>
      <div class="filter"></div>
      <div class="pic">
        <% unless @highlights.third[:pic].nil? %>
          <%= image_tag @highlights.third[:pic] %>
        <% else %>
          <%= image_tag 'bg/dummy-3.png' %>
        <% end %>
      </div>
      <div class="title-wrapper">
        <div class="title">
          <%= @highlights.third[:title] %>
        </div>
      </div>
    <% end %>
  <% else %>
    <%= link_to '#', class:'element pos-3' do %>
      <div class="filter"></div>
      <div class="pic">
        <%= image_tag 'bg/dummy-3.png' %>
      </div>
      <div class="title-wrapper">
        <div class="title">
          Content goes here
        </div>
      </div>
    <% end %>
  <% end %>

</section>

<section class="latest-posts">
  <div class="latest-posts-line">
    <%= link_to posts_path, class: 'post-collection-link' do %>
      <h2>Latest posts.</h2>
    <% end %>
    <div>
      <% @post_types.each_with_index do |type, index| %>
        <%= link_to type.name, type, class: 'post-type' %>
        <%= bar_separator(index, @post_types.count) %>
      <% end %>
      <i class="fa fa-tags" aria-hidden="true"></i>
    </div>
  </div>
  <%= render partial: "shared/posts", locals: {posts: @latest_posts, pics: false} %>
</section>